# .github/workflows/ci.yml
name: ci

on: [push, pull_request]

jobs:
  ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    with:
      enable_phpmd: true
      disable_phpcpd: true
      extra_plugin_runners: moodle-plugin-ci add-plugin mdjnelson/moodle-mod_customcert --branch MOODLE_401_STABLE